# Generated by Django 6.0.2 on 2026-03-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantfeedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistantfeedback',
            new_name='assistant_a_event_t_90f162_idx',
            old_name='assistant_f_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantfeedback',
            new_name='assistant_a_sent_to_5412ea_idx',
            old_name='assistant_f_sent_to_idx',
        ),
    ]
